import 'package:flutter/material.dart';

const appColorPrimary = Color(0XFF6200EE);
const appColorPrimaryDark = Color(0XFF3700B3);
const appColorAccent = Color(0XFF03DAC5);
const appTextColorPrimary = Color(0XFF212121);
const appTextColorSecondary = Color(0XFF5A5C5E);
const appLayout_background = Color(0XFFf8f8f8);
const appWhite = Color(0XFFFFFFFF);
const appLight_purple = Color(0XFFdee1ff);
const appLight_orange = Color(0XFFffddd5);
const appLight_parrot_green = Color(0XFFb4ef93);
const appIconTintCherry = Color(0XFFffddd5);
const appIconTint_sky_blue = Color(0XFF73d8d4);
const appIconTint_mustard_yellow = Color(0XFFffc980);
const appIconTintDark_purple = Color(0XFF8998ff);
const appTxtTintDark_purple = Color(0XFF515BBE);
const appIconTintDarkCherry = Color(0XFFf2866c);
const appIconTintDark_sky_blue = Color(0XFF73d8d4);
const appDark_parrot_green = Color(0XFF5BC136);
const appDarkRed = Color(0XFFF06263);
const appLightRed = Color(0XFFF89B9D);
const appCat1 = Color(0XFF8998FE);
const appCat2 = Color(0XFFFF9781);
const appCat3 = Color(0XFF73D7D3);
const appShadowColor = Color(0X95E9EBF0);
const appColorPrimaryLight = Color(0XFFF9FAFF);
